import { describe, it, expect, beforeEach } from 'vitest';
import { AdapterRegistry, AdapterRegistryError } from '../src/adapters/registry.js';
import type { Adapter, OutputFormat } from '../src/adapters/types.js';

/**
 * Feature: multi-format-adapter
 * Property 2: 注册表 CRUD 一致性
 * Validates: Requirements 3.1, 3.2, 3.3, 3.5, 3.6
 */

/**
 * Create a valid adapter for testing
 */
function createValidAdapter(name: string, outputFormat: OutputFormat = 'ts'): Adapter {
    return {
        name,
        outputFormat,
        defaultOutputPath: `output/${name}.${outputFormat}`,
        detect: async () => true,
        generate: () => `// Generated by ${name}`
    };
}

describe('AdapterRegistry', () => {
    let registry: AdapterRegistry;

    beforeEach(() => {
        registry = new AdapterRegistry();
    });

    describe('register()', () => {
        it('should register a valid adapter', () => {
            const adapter = createValidAdapter('test-adapter');
            expect(() => registry.register(adapter)).not.toThrow();
        });

        it('should throw error when registering duplicate adapter name', () => {
            const adapter1 = createValidAdapter('duplicate');
            const adapter2 = createValidAdapter('duplicate', 'json');

            registry.register(adapter1);
            expect(() => registry.register(adapter2)).toThrow(AdapterRegistryError);
            expect(() => registry.register(adapter2)).toThrow('Adapter "duplicate" is already registered');
        });

        it('should throw error when adapter is missing required property', () => {
            const invalidAdapter = {
                outputFormat: 'ts',
                defaultOutputPath: 'output.ts',
                detect: async () => true,
                generate: () => ''
            } as unknown as Adapter;

            expect(() => registry.register(invalidAdapter)).toThrow(AdapterRegistryError);
            expect(() => registry.register(invalidAdapter)).toThrow('missing required property "name"');
        });

        it('should throw error when adapter is missing detect method', () => {
            const invalidAdapter = {
                name: 'invalid',
                outputFormat: 'ts',
                defaultOutputPath: 'output.ts',
                generate: () => ''
            } as unknown as Adapter;

            expect(() => registry.register(invalidAdapter)).toThrow(AdapterRegistryError);
            expect(() => registry.register(invalidAdapter)).toThrow('missing required property "detect"');
        });
    });

    describe('get()', () => {
        it('should return registered adapter by name', () => {
            const adapter = createValidAdapter('my-adapter');
            registry.register(adapter);

            const retrieved = registry.get('my-adapter');
            expect(retrieved).toBe(adapter);
            expect(retrieved.name).toBe('my-adapter');
        });

        it('should throw error when adapter is not registered', () => {
            expect(() => registry.get('nonexistent')).toThrow(AdapterRegistryError);
            expect(() => registry.get('nonexistent')).toThrow('Adapter "nonexistent" is not registered');
        });
    });

    describe('list()', () => {
        it('should return empty array when no adapters registered', () => {
            expect(registry.list()).toEqual([]);
        });

        it('should return all registered adapter names', () => {
            registry.register(createValidAdapter('adapter-a'));
            registry.register(createValidAdapter('adapter-b'));
            registry.register(createValidAdapter('adapter-c'));

            const names = registry.list();
            expect(names).toHaveLength(3);
            expect(names).toContain('adapter-a');
            expect(names).toContain('adapter-b');
            expect(names).toContain('adapter-c');
        });
    });

    describe('detectAll()', () => {
        it('should return names of adapters that detect their framework', async () => {
            const alwaysDetect = createValidAdapter('always');
            const neverDetect: Adapter = {
                ...createValidAdapter('never'),
                detect: async () => false
            };

            registry.register(alwaysDetect);
            registry.register(neverDetect);

            const detected = await registry.detectAll('/some/path');
            expect(detected).toContain('always');
            expect(detected).not.toContain('never');
        });

        it('should handle detection errors gracefully', async () => {
            const errorAdapter: Adapter = {
                ...createValidAdapter('error-adapter'),
                detect: async () => { throw new Error('Detection failed'); }
            };

            registry.register(errorAdapter);

            const detected = await registry.detectAll('/some/path');
            expect(detected).not.toContain('error-adapter');
        });
    });
});
