import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Adapter, OutputFormat } from './types.js';
import type { DocNode } from '../type/docNode.js';
import { getEffectiveDisplayName, isIgnored } from '../metaSort.js';

/**
 * VitePress sidebar item structure
 */
interface VitePressSidebarItem {
    text: string;
    link?: string;
    items?: VitePressSidebarItem[];
    collapsed?: boolean;
}

/**
 * VitePressAdapter - Adapter for generating VitePress sidebar configuration
 * 
 * This adapter generates TypeScript sidebar configuration files that can be
 * imported into VitePress config.ts. It transforms the DocNode tree into
 * VitePress's sidebar format with text, link, items, and collapsed properties.
 * 
 * @description
 * - detect() checks for .vitepress directory or vitepress dependency in package.json
 * - generate() converts DocNode tree to VitePress sidebar format
 * - Links have .md extension removed per VitePress conventions
 */
export class VitePressAdapter implements Adapter {
    readonly name = 'vitepress';
    readonly outputFormat: OutputFormat = 'ts';
    readonly defaultOutputPath = '.vitepress/sidebar.ts';

    /**
     * Detect if VitePress is present in the project
     * @param rootPath - Project root directory path
     * @returns true if .vitepress directory exists or vitepress is in package.json dependencies
     */
    async detect(rootPath: string): Promise<boolean> {
        // Check for .vitepress directory
        const vitepressDir = join(rootPath, '.vitepress');
        if (existsSync(vitepressDir)) {
            return true;
        }

        // Check for vitepress in package.json
        const packageJsonPath = join(rootPath, 'package.json');
        if (existsSync(packageJsonPath)) {
            try {
                const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
                const deps = {
                    ...packageJson.dependencies,
                    ...packageJson.devDependencies,
                };
                if ('vitepress' in deps) {
                    return true;
                }
            } catch {
                // Ignore JSON parse errors
            }
        }

        return false;
    }

    /**
     * Generate VitePress sidebar configuration from DocNode tree
     * @param nodes - Array of DocNode representing the document tree
     * @param options - Generation options
     * @returns TypeScript file content with sidebar configuration
     */
    generate(nodes: DocNode[]): string {
        const sidebarItems = this.convertToSidebarItems(nodes);
        const sidebarJson = JSON.stringify(sidebarItems, null, 2);
        
        // Generate TypeScript file content
        const lines = [
            '// Auto-generated by doctoc - DO NOT EDIT',
            '// This file is automatically generated. Any manual changes will be overwritten.',
            '',
            'import type { DefaultTheme } from \'vitepress\';',
            '',
            `export const sidebar: DefaultTheme.SidebarItem[] = ${sidebarJson};`,
            '',
        ];

        return lines.join('\n');
    }

    /**
     * Get import hint for users on how to use the generated sidebar file
     * @returns Import hint string explaining how to integrate the sidebar
     */
    getImportHint(): string {
        return `To use the generated sidebar in your VitePress config:

// .vitepress/config.ts
import { sidebar } from './sidebar'

export default {
  themeConfig: {
    sidebar
  }
}`;
    }

    /**
     * Convert DocNode array to VitePress sidebar items
     * @param nodes - Array of DocNode
     * @returns Array of VitePress sidebar items
     */
    private convertToSidebarItems(nodes: DocNode[]): VitePressSidebarItem[] {
        const items: VitePressSidebarItem[] = [];

        for (const node of nodes) {
            // Skip ignored nodes
            if (isIgnored(node)) {
                continue;
            }

            const item = this.convertNodeToSidebarItem(node);
            if (item) {
                items.push(item);
            }
        }

        return items;
    }

    /**
     * Convert a single DocNode to VitePress sidebar item
     * @param node - DocNode to convert
     * @returns VitePress sidebar item or null if should be skipped
     */
    private convertNodeToSidebarItem(node: DocNode): VitePressSidebarItem | null {
        const text = getEffectiveDisplayName(node);

        if (node.type === 'file') {
            // File node: has text and link
            const link = this.formatLink(node.linkPath || node.path);
            return { text, link };
        } else {
            // Directory node: has text, items, and collapsed
            const children = node.children 
                ? this.convertToSidebarItems(node.children)
                : [];

            // Only include directory if it has children
            if (children.length === 0) {
                return null;
            }

            return {
                text,
                items: children,
                collapsed: false,
            };
        }
    }

    /**
     * Format link path for VitePress
     * - Remove .md extension (VitePress convention)
     * - Ensure path starts with /
     * @param path - Original path
     * @returns Formatted link path
     */
    private formatLink(path: string): string {
        // Remove .md extension
        let link = path.replace(/\.md$/, '');
        
        // Ensure path starts with /
        if (!link.startsWith('/')) {
            link = '/' + link;
        }

        return link;
    }
}

/**
 * Singleton instance of VitePressAdapter
 */
export const vitepressAdapter = new VitePressAdapter();
