/**
 * Adapter Output Writer Module
 * 
 * Handles writing adapter-generated content to output files.
 * Key features:
 * - Generates standalone config files (non-invasive)
 * - Adds auto-generated declaration comments at file top
 * - Supports overwriting existing output files
 */

import fs from 'fs/promises';
import { dirname } from 'node:path';
import type { OutputFormat } from './types.js';

/**
 * Auto-generated comment templates for different output formats
 */
const AUTO_GENERATED_COMMENTS: Record<OutputFormat, string> = {
    ts: '// @generated - This file is auto-generated by doc-toc. Do not edit manually.',
    js: '// @generated - This file is auto-generated by doc-toc. Do not edit manually.',
    json: '',  // JSON doesn't support comments, handled separately
    yaml: '# @generated - This file is auto-generated by doc-toc. Do not edit manually.',
    md: '<!-- @generated - This file is auto-generated by doc-toc. Do not edit manually. -->'
};

/**
 * Result of a write operation
 */
export interface WriteResult {
    /** Whether the write succeeded */
    success: boolean;
    /** Output file path */
    outputPath: string;
    /** Result message */
    message: string;
}

/**
 * Options for writing adapter output
 */
export interface WriteOptions {
    /** Output file path (absolute) */
    outputPath: string;
    /** Content to write */
    content: string;
    /** Output format (determines comment style) */
    outputFormat: OutputFormat;
}

/**
 * Add auto-generated declaration comment to content
 * 
 * @param content - Original content
 * @param outputFormat - Output format type
 * @returns Content with auto-generated comment prepended
 */
export function addAutoGeneratedComment(content: string, outputFormat: OutputFormat): string {
    const comment = AUTO_GENERATED_COMMENTS[outputFormat];
    
    // JSON doesn't support comments, return content as-is
    if (outputFormat === 'json') {
        return content;
    }
    
    // Prepend comment with newline
    if (comment) {
        return `${comment}\n\n${content}`;
    }
    
    return content;
}

/**
 * Write adapter output to file
 * 
 * Features:
 * - Creates parent directories if they don't exist
 * - Adds auto-generated comment at file top
 * - Overwrites existing files
 * 
 * @param options - Write options
 * @returns Write result
 */
export async function writeAdapterOutput(options: WriteOptions): Promise<WriteResult> {
    const { outputPath, content, outputFormat } = options;
    
    try {
        // Add auto-generated comment
        const finalContent = addAutoGeneratedComment(content, outputFormat);
        
        // Ensure parent directory exists
        const dir = dirname(outputPath);
        await fs.mkdir(dir, { recursive: true });
        
        // Write file (overwrites if exists)
        await fs.writeFile(outputPath, finalContent, 'utf-8');
        
        return {
            success: true,
            outputPath,
            message: `Successfully wrote to ${outputPath}`
        };
    } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        return {
            success: false,
            outputPath,
            message: `Failed to write ${outputPath}: ${errorMessage}`
        };
    }
}

/**
 * Check if content has auto-generated marker
 * Useful for detecting if a file was previously generated
 * 
 * @param content - File content to check
 * @returns true if content contains auto-generated marker
 */
export function hasAutoGeneratedMarker(content: string): boolean {
    return content.includes('@generated') || content.includes('Auto-generated');
}
