// @generated - This file is auto-generated by doc-toc. Do not edit manually.

// Auto-generated by doctoc - DO NOT EDIT
// This file is automatically generated. Any manual changes will be overwritten.

import type { DefaultTheme } from 'vitepress';

export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    "text": "第一章",
    "items": [
      {
        "text": "测试的重要性",
        "link": "/docs/第一章/test"
      }
    ],
    "collapsed": false
  },
  {
    "text": "第二章",
    "items": [
      {
        "text": "学习多智能体",
        "link": "/docs/第二章/test"
      }
    ],
    "collapsed": false
  },
  {
    "text": "第三章",
    "items": [
      {
        "text": "学习智能体",
        "link": "/docs/第三章/test"
      }
    ],
    "collapsed": false
  },
  {
    "text": "第四章",
    "items": [
      {
        "text": "你好",
        "link": "/docs/第四章/test"
      }
    ],
    "collapsed": false
  }
];
